= LibreLingo Documentation on Course

A *Course* is the highest element on the course structure. It contains modules, which in turn contains skills. There are usually one course for each language.

To get a better understanding, you can explore the https://github.com/kantord/LibreLingo/tree/main/courses[`courses` directory] on this repository and read the link:README.md#basics[course basics].

'''

*Confused?*
https://github.com/kantord/LibreLingo/discussions[Ask people] on GitHub Discussions.

'''

*Table of Contents:*

* <<tree-structure,Tree structure>>
* <<yaml,`course.yaml`>>
 ** <<data-breakdown,Data breakdown>>

== Tree structure

A typical tree structure for a course is like this:

----
courses/spanish-from-english/
├── activities
│   ├── module.yaml
│   └── skills
│       ├── continuous.yaml
│       └── ser_estar.yaml
├── basics
│   ├── module.yaml
│   └── skills
│       ├── animals.yaml
│       ├── clothes.yaml
│       ├── food.yaml
│       ├── nature.yaml
│       ├── plurals.yaml
│       ├── professions.yaml
│       ├── verb_plurals.yaml
│       └── verbs.yaml
├── course.yaml
└── introduction
    ├── module.yaml
    └── skills
        ├── adjectives.yaml
        ├── phrases.yaml
        └── preferences.yaml
----

Here, `activities`, `basics` and `introduction` are xref:module.adoc[modules]. The `continuous.yaml`, `animals.yaml` etc. are xref:skill.adoc[skills]. Directly inside the course directory there is also a file called `course.yaml`. This file contains information about the course (<<yaml,see below>>).

A course directory name should not have spaces and should be written in `slug-form` in plain English.

+++<a id="yaml">++++++</a>+++

== `course.yaml`

A `course.yaml` file for the Spanish course looks like this:

[,yaml]
----
# This file contains generic meta-data about the course

Course:
  Language:
    Name: Spanish
    IETF BCP 47: es
  For speakers of:
    Name: English
    IETF BCP 47: en
  License:
    Name: Attribution-ShareAlike 4.0 International
    Short name: CC BY-SA 4.0
    Link: https://creativecommons.org/licenses/by-sa/4.0/legalcode
  Special characters:
    - "á"
    - "Á"
    - "é"
    - "É"
    - "í"
    - "Í"
    - "ó"
    - "Ó"
    - "ú"
    - "Ú"
    - "ü"
    - "Ü"
    - "ñ"
    - "Ñ"
    - "¿"
    - "¡"

Modules:
  - basics/
  - introduction/
  - activities/
----

+++<a id="data-breakdown">++++++</a>+++

=== Data breakdown

*`Course`* has information about the course.

* `Language`
 ** `Language > Name`: The name of the language you want to test for or teach.
 ** `Language > IETF BCP 47`: The IETF BCP 47 code of the above language. List available http://www.iana.org/assignments/language-subtag-registry[here].
* `For speakers of`
 ** `For speakers of > Name`: The name of the language your target audience already speaks.
 ** `For speakers of > IETF BCP 47`: The IETF BCP 47 code of the above language. List available http://www.iana.org/assignments/language-subtag-registry[here].
* `License`
 ** `License > Name`: Full license name under which your course is made available. In most cases it's ok to keep it as is.
 ** `License > Short name`: Short name for the license. e.g. `CC BY-SA 4.0`
 ** `License > Link`: URL to reach to the full text of the license. e.g. `+https://creativecommons.org/licenses/by-sa/4.0/legalcode+`
* `Special characters`: An array of special characters that might not be present on a typical English keyboard.

*`Modules`* has a list of module directory names followed by a `/`.
