version: v1.0
name: Node JS
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Install dependencies
    task:
      jobs:
        - name: yarn install
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - cache restore cypress-$(checksum yarn.lock)
            - cache restore packages-web-$(checksum yarn.lock)
            - yarn install --frozen-lockfile
            - yarn cypress install
            - cache store node-$(checksum yarn.lock) node_modules
            - cache store cypress-$(checksum yarn.lock) /home/semaphore/.cache/Cypress
            - cache store packages-web-$(checksum yarn.lock) workspaces/web/node_modules
    dependencies: []
  - name: Jest
    task:
      jobs:
        - name: jest
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - yarn jest
    dependencies:
      - Eslint
  - name: Cypress
    task:
      jobs:
        - name: cypress
          parallelism: 3
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - cache restore cypress-$(checksum yarn.lock)
            - cache restore packages-web-$(checksum yarn.lock)
            - cache restore sapper-build-$SEMAPHORE_GIT_PR_SHA
            - yarn install
            - SEMAPHORE_BUILD_NUMBER=$SEMAPHORE_PIPELINE_ID SEMAPHORE_THREAD_COUNT=3 yarn test
      secrets:
        - name: Percy token
        - name: KnapsackPro token
    dependencies:
      - Sapper build
  - name: Eslint
    dependencies:
      - Install dependencies
    task:
      jobs:
        - name: eslint
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - yarn eslint workspaces/*/src
  - name: Eslint Cypress
    dependencies:
      - Install dependencies
    task:
      jobs:
        - name: eslint
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - yarn eslint workspaces/*/cypress
  - name: Python Code Style Check
    dependencies: []
    task:
      jobs:
        - name: pycodestyle
          commands:
            - sem-version python 3.8
            - checkout
            - pip install pipenv
            - pipenv install
            - pycodestyle . --exclude="course/migrations" --max-line-length 119
  - name: Django test
    dependencies:
      - Python Code Style Check
    task:
      jobs:
        - name: manage.py test
          commands:
            - sem-version python 3.8
            - checkout
            - pip install pipenv
            - pipenv install
            - 'DATABASE_URL=sqlite:///db.sqlite3 python manage.py test'
  - name: Sapper build
    dependencies:
      - Eslint Cypress
    task:
      jobs:
        - name: yarn web build
          commands:
            - sem-version node 12
            - checkout
            - cache restore node-$(checksum yarn.lock)
            - cache restore cypress-$(checksum yarn.lock)
            - cache restore packages-web-$(checksum yarn.lock)
            - yarn web build
            - cache store sapper-build-$SEMAPHORE_GIT_PR_SHA workspaces/web/__sapper__
promotions:
  - name: Deploy to production
    pipeline_file: pipeline_2.yml
    auto_promote:
      when: branch = 'master' AND result = 'passed'
